//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public Ad()
        {
            this.AdsCampaigns = new HashSet<AdsCampaign>();
        }
    
        public string ID { get; set; }
        public string ReceiptNo { get; set; }
        public int Status { get; set; }
        public string User_ID { get; set; }
        public string AdsPackage_ID { get; set; }
        public int Increment { get; set; }
    
        public virtual AdsPackage AdsPackage { get; set; }
        public virtual ICollection<AdsCampaign> AdsCampaigns { get; set; }
    }
}
