//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsCampaignBanner
    {
        public string ID { get; set; }
        public string AdsCampaign_ID { get; set; }
        public string ImageUrl { get; set; }
        public int Increment { get; set; }
    
        public virtual AdsCampaign AdsCampaign { get; set; }
    }
}
