//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdsHistory
    {
        public string ID { get; set; }
        public string TicketNo { get; set; }
        public string Ads_ID { get; set; }
        public int Task { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateExpired { get; set; }
    }
}
