//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.BlogPostMedias = new HashSet<BlogPostMedia>();
        }
    
        public string ID { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string URL { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CoverImage { get; set; }
        public string Author_ID { get; set; }
        public string User_ID { get; set; }
        public bool IsPublished { get; set; }
        public bool IsArchived { get; set; }
        public int Increment { get; set; }
    
        public virtual ICollection<BlogPostMedia> BlogPostMedias { get; set; }
    }
}
