//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostMedia
    {
        public string ID { get; set; }
        public string URL { get; set; }
        public string BlogPost_ID { get; set; }
        public int Increment { get; set; }
        public string Author_ID { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
