//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentCategory
    {
        public ContentCategory()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public string ID { get; set; }
        public string CategoryTitle { get; set; }
        public string Description { get; set; }
        public int PageSection { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Increment { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
    }
}
