//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.States = new HashSet<State>();
        }
    
        public string ID { get; set; }
        public string CountryName { get; set; }
        public string LocalName { get; set; }
        public string WebCode { get; set; }
        public string Region { get; set; }
        public string Continent { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string SurfaceArea { get; set; }
        public string Population { get; set; }
        public int Increment { get; set; }
    
        public virtual ICollection<State> States { get; set; }
    }
}
