//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASDBEntities : DbContext
    {
        public FASDBEntities()
            : base("name=FASDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountListingPackage> AccountListingPackages { get; set; }
        public DbSet<AccountListing> AccountListings { get; set; }
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Ad> Ads { get; set; }
        public DbSet<AdsCampaignBanner> AdsCampaignBanners { get; set; }
        public DbSet<AdsCampaign> AdsCampaigns { get; set; }
        public DbSet<AdsHistory> AdsHistories { get; set; }
        public DbSet<AdsPackage> AdsPackages { get; set; }
        public DbSet<BlogPostMedia> BlogPostMedias { get; set; }
        public DbSet<BlogPost> BlogPosts { get; set; }
        public DbSet<BusinessCategory> BusinessCategories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContentCategory> ContentCategories { get; set; }
        public DbSet<ContentImage> ContentImages { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<NewsletterSubscriber> NewsletterSubscribers { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserAuthentication> UserAuthentications { get; set; }
        public DbSet<UserBusiness> UserBusinesses { get; set; }
        public DbSet<UserClient> UserClients { get; set; }
        public DbSet<UserComment> UserComments { get; set; }
        public DbSet<UserComplaint> UserComplaints { get; set; }
        public DbSet<UserEducationalQualification> UserEducationalQualifications { get; set; }
        public DbSet<UserIndividual> UserIndividuals { get; set; }
        public DbSet<UserJobBoxNotification> UserJobBoxNotifications { get; set; }
        public DbSet<UserJobBoxNotificationStatu> UserJobBoxNotificationStatus { get; set; }
        public DbSet<UserPortfolioItem> UserPortfolioItems { get; set; }
        public DbSet<UserRating> UserRatings { get; set; }
        public DbSet<UserSolution> UserSolutions { get; set; }
        public DbSet<UserWorkExperience> UserWorkExperiences { get; set; }
    }
}
