//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public string ID { get; set; }
        public string User_ID { get; set; }
        public string Owner_ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime DatetCommented { get; set; }
        public int Increment { get; set; }
    }
}
