//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBusiness
    {
        public string ID { get; set; }
        public string Email { get; set; }
        public string BusinessCategory_ID { get; set; }
        public string BusinessName { get; set; }
        public string BusinessDescription { get; set; }
        public string Website { get; set; }
        public string Country_ID { get; set; }
        public string State_ID { get; set; }
        public string City_ID { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsSubscribed { get; set; }
        public bool IsCertified { get; set; }
        public bool IsQuarantined { get; set; }
        public bool IsApproved { get; set; }
        public bool IsAgreedToTerms { get; set; }
        public string ContactNumber { get; set; }
        public string ContactAddress { get; set; }
        public string ImageUrl { get; set; }
        public string CoverImageUrl { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int Increment { get; set; }
    }
}
