//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAService_WebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserJobBoxNotification
    {
        public string ID { get; set; }
        public string Recepient { get; set; }
        public string RecepientLocation { get; set; }
        public string Sender { get; set; }
        public string SenderLocation { get; set; }
        public string Message { get; set; }
        public System.DateTime DateSent { get; set; }
        public bool IsGroupMessage { get; set; }
        public int Increment { get; set; }
    }
}
